/* auto-generated by NAPI-RS */

/**
 * Statistics for a publisher
 */
export interface PublisherStats {
  /** Number of messages published */
  messages: number
  /** Total bytes published */
  bytes: number
}

/**
 * Main node for creating publishers and subscribers
 */
export class AgenticNode {
  /**
   * Create a new AgenticNode
   * @param name - Name of the node
   */
  constructor(name: string)

  /**
   * Create a publisher for a topic
   * @param topic - Topic name
   * @returns A publisher instance
   */
  createPublisher(topic: string): Promise<AgenticPublisher>

  /**
   * Create a subscriber for a topic
   * @param topic - Topic name
   * @returns A subscriber instance
   */
  createSubscriber(topic: string): Promise<AgenticSubscriber>
}

/**
 * Publisher for sending messages to a topic
 */
export class AgenticPublisher {
  /**
   * Publish a message to the topic
   * @param data - JSON string data to publish
   */
  publish(data: string): Promise<void>

  /**
   * Get publisher statistics
   * @returns Statistics about published messages
   */
  getStats(): PublisherStats
}

/**
 * Subscriber for receiving messages from a topic
 */
export class AgenticSubscriber {
  /**
   * Try to receive a message (non-blocking)
   * @returns Message as JSON string, or null if no message available
   */
  tryRecv(): Promise<string | null>

  /**
   * Receive a message (blocking)
   * @returns Message as JSON string
   */
  recv(): Promise<string>
}
